In [41]:
#overview of AI/ML/DS-Practicals
#python basics
#libraries--
#inbuilt methods-- 
#numpy over list
#maths stats operations/array operations
#exercise/assignment
#shift+tab--
#google classroom--

#!pip install numpy

In [2]:
import numpy as np

In [5]:
l=[1,2,3,4,5]

In [6]:
type(l)

list

In [1]:
np.array

NameError: name 'np' is not defined

In [2]:
np.array()

NameError: name 'np' is not defined

In [9]:
np.array(l)

array([1, 2, 3, 4, 5])

In [10]:
x=np.array(l)

In [11]:
x

array([1, 2, 3, 4, 5])

In [12]:
type(x)

numpy.ndarray

In [13]:
x.ndim()

1

In [14]:
x.shape

(5,)

In [31]:
x=np.array(l,dtype=float,ndmin=2)

In [32]:
x

array([[1., 2., 3., 4., 5.]])

In [33]:
x=np.array(l,float,ndmin=2)

In [34]:
x

array([[1., 2., 3., 4., 5.]])

In [17]:
type(x)

numpy.ndarray

In [18]:
x.dtype

dtype('int32')

In [19]:
x.ndim

2

In [20]:
x.shape

(1, 5)

In [22]:
range(0,6)

range(0, 6)

In [24]:
for i in range(0,6):
    print(i,end='\t')

0	1	2	3	4	5	

In [25]:
for i in range(0,6):
    print(i,end=' ')

0 1 2 3 4 5 

In [26]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [27]:
np.arange(3,6)

array([3, 4, 5])

In [28]:
np.arange(1,6,3)

array([1, 4])

In [29]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [30]:
#we dont need to iterate using for loop

In [35]:
x

array([[1., 2., 3., 4., 5.]])

In [36]:
a=np.array([8,9,10])

In [37]:
a

array([ 8,  9, 10])

In [38]:
a.reshape(1,3)

array([[ 8,  9, 10]])

In [39]:
a.reshape(3,1)

array([[ 8],
       [ 9],
       [10]])

In [40]:
a.reshape(1,3).ndim

2

In [42]:
#numpy over list:-

In [43]:
b=[5,6,7,8,9]

In [44]:
#every no to be added by its own -[10,12,14,16,18]

In [46]:
c=[]
for i in b:
    x=i+i
    c.append(x)
print(c)
    

[10, 12, 14, 16, 18]


In [47]:
y=np.array(b)

In [48]:
y+y

array([10, 12, 14, 16, 18])

In [49]:
l1=[1,2,3,4,5]
l2=[5,6,7,8,9]

In [50]:
#[6,8,10,12,14]

In [51]:
l1+l2

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]

In [52]:
x=np.array(l1)
y=np.array(l2)

In [53]:
x+y

array([ 6,  8, 10, 12, 14])

In [54]:
l=[1,2,3,4,5]

In [55]:
#[1,2,99,99,99]

In [56]:
l[2:4+1]

[3, 4, 5]

In [57]:
l[2:5]

[3, 4, 5]

In [58]:
l[2:]

[3, 4, 5]

In [59]:
l[2:]=99

TypeError: can only assign an iterable

In [60]:
l[2:]='99'

In [61]:
l

[1, 2, '9', '9']

In [62]:
l

[1, 2, '9', '9']

In [63]:
x=[1,2,3,4,5]

In [64]:
y=np.array(x)

In [65]:
y

array([1, 2, 3, 4, 5])

In [67]:
y[2:]=99

In [68]:
y #broadcasting is possible here

array([ 1,  2, 99, 99, 99])

In [70]:
l=[1,2,3,4,5,6,7,8,9]

In [71]:
#no which is greater than 5

In [72]:
l>5

TypeError: '>' not supported between instances of 'list' and 'int'

In [75]:
x=np.array(l)

In [76]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [79]:
x[x>5] #comparision operator is possible here

array([6, 7, 8, 9])

In [81]:
#convert height in cm:
l=[14,23,67,11] #m

In [82]:
np.array(l)*100

array([1400, 2300, 6700, 1100])

In [85]:
x=np.arange(0,16)

In [86]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [87]:
x.max()

15

In [88]:
x.argmax()

15

In [89]:
x.argmin()

0

In [90]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [91]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [92]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [95]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [106]:
np.random.rand(2,3)

array([[0.88361837, 0.09527905, 0.27846392],
       [0.27433929, 0.91746367, 0.34010391]])

In [98]:
np.random.randn(2,4)

array([[ 0.26575714,  0.39748093, -1.67568476,  0.58192319],
       [ 0.47014036,  0.11094243,  0.7900111 ,  0.47675903]])

In [99]:
np.random.randint(3,8,12)

array([7, 6, 6, 4, 5, 4, 7, 6, 7, 3, 5, 7])

In [100]:
np.random.randint(3,8,(3,4))

array([[3, 7, 5, 7],
       [4, 4, 7, 5],
       [7, 5, 7, 4]])

In [101]:
#slicing +indexing

In [102]:
# operations

In [103]:
#exercise--Asgn

In [107]:
M

SyntaxError: invalid syntax (598798306.py, line 1)